version: "2"

linters:
  enable:
    - dogsled
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - staticcheck
    - govet
    - misspell
    - nestif
    - prealloc
    - revive
    - unconvert
    - unparam

  settings:
    revive:
      severity: warning

  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
